# Generated by Django 5.2.4 on 2025-08-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_organizador_genero_alter_participante_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagem_banner',
            field=models.ImageField(default='', upload_to='banners/'),
            preserve_default=False,
        ),
    ]
