# Generated by Django 5.2.4 on 2025-08-07 04:30

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_evento_imagem_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagem_banner',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='banners/'),
        ),
    ]
