# Generated by Django 5.2.4 on 2025-08-07 23:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_evento_imagem_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagem_banner',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
