# Generated by Django 5.2.4 on 2025-08-08 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_evento_imagem_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='participante',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.participante'),
            preserve_default=False,
        ),
    ]
