# Generated by Django 5.2.4 on 2025-08-08 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_inscricao_participante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='email',
        ),
    ]
