# Generated by Django 5.2.4 on 2025-08-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_organizador_email_remove_participante_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='email',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='telefone',
        ),
    ]
